/* Replace with your SQL commands */
CREATE TABLE IF NOT EXISTS app_user (
	id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	email VARCHAR (255) UNIQUE NOT NULL,
	password  VARCHAR (255) NOT NULL
);
